### ISSUE TITLE
Add support for testing event pattern

### ISSUE THREAD

**Issue by jens-peterolsson** [ljacobsson/evb-cli#2] opened 2020-04-03 09:29 UTC
So an example json event can be pasted into to the console and the command will return if a given pattern matches or not.

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_TestEventPattern.html

**Comment by ljacobsson** [comment] 2020-11-04 12:44
Just realised this is a duplicate of the just fixed #8 

Closing

**Closed as completed by ljacobsson** 2020-11-04 12:44 UTC
